### ISSUE TITLE
a few questions about neovim config

### ISSUE THREAD

**Issue by ghost** [otommod/dotfiles#1]
```
(fn group-by [n seq ?from]
  (fn f [seq i]
    (let [i (+ i n)
          j (+ i n -1)]
      (when (< i (length seq))
        (values i (unpack seq i j)))))
  (let [start-idx (if (nil? ?from) 1 ?from)]
    (values f seq (- start-idx n))))
```

Hello, I'm refering to your neovim config. What is the usage of this unpack...
Could you leave email for communication?

**Comment by otommod** [comment]
Hello!  Sorry for the late reply.  I hope a comment is fine.

The `unpack` here allows returning the values in the `i` to `j` indices of the sequential table `seq` as multiple values which you can then easily assign to a loop variable.

Basically, I wrote this iterator because I really like using the `collect` and `icollect` macros in Fennel and this allows me to do [stuff like this](https://github.com/otommod/dotfiles/blob/4b96e3836849eef603d8080529d1bf17bdc7e343/nvim/.config/nvim/fnl/rc/macros.fnl#L58-L59).  You can also do this with the new `fcollect` but it's not as clean.

Hope this answers your question!

**Comment by ghost** [comment]
Thank for your answers very much☺️
